### ISSUE TITLE
formContainer: setting a backbone model 

### ISSUE THREAD

**Issue by toh82** [Paratron/modoJS#1]
I see no description how a backbone model is added on the formContainer, from browsing though examples it's often done by `params.data = model`.

I checked the code about that an could find out that `settings.data` is set to `null` and never changed by any config value except `params.defaultData` which is written into `setting.data` if it is empty.

Is that a bug or should the model here be set to `params.defaultData`?

**Comment by Paratron** [comment]
A FormContainer will follow the same get/set principles like many other objects.

Simply call `myContainer.set(myModel)` to pass a models properties to all contained form elements with keys fitting to the model properties.

**Comment by Paratron** [comment]
Closed, because does not apply anymore. V2 will be React based.
