### ISSUE TITLE
Modo.List declarative example uses "Container"

### ISSUE THREAD

**Issue by toh82** [Paratron/modoJS#2]
shouldn't the declarative example on http://docs.modojs.com/en/reference/list show `type: 'List'` instead of `type: 'Container'`?

**Comment by Paratron** [comment]
Yup, looks like I never created the declarative List example - that was still a copy from the declarative example for the Container element.

I've just pushed the recent version 1.1.3 to the website and updated all the demos to use the most recent version of the library. In the course of doing that, I also added a declarative example to the modo.List element.
